{% set python_min = "3.10" %}
{% set name = "xarray-safe-rcm" %}
{% set version = "2026.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a8ce9e7dec639cf3d4306b714e52d266648fe93eba721afc52b4b2efde5c4bdc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - cytoolz
    - numpy
    - xarray
    - xarray-datatree
    - fsspec
    - lxml
    - xmlschema
    - rioxarray
    - exceptiongroup

test:
  imports:
    - safe_rcm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/umr-lops/xarray-safe-rcm
  summary: xarray reader for radarsat constellation mission (RCM) SAFE files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - agrouaze
    - vincelhx
    - Skealz
