{% set name = "xarray-safe-rcm" %}
{% set version = "2023.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-safe-rcm-{{ version }}.tar.gz
  sha256: 46d3bbff729f7b279ad1d78cd49202a4ab7ad311b9ec1bdbc9e7b8009008938f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - cytoolz
    - numpy
    - xarray
    - xarray-datatree
    - fsspec
    - lxml
    - xmlschema
    - rioxarray
    - exceptiongroup

test:
  imports:
    - safe_rcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xarray-safe-rcm
  summary: xarray reader for radarsat constellation mission (RCM) SAFE files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - agrouaze
